duraark-sessions:
  image: duraark/duraark-sessions:latest
  ports:
    - "5011:5011"
  volumes:
    - /duraark-storage:/duraark-storage

duraark-metadata:
  image: duraark/duraark-metadata:latest
  ports:
    - "5012:5012"
  volumes_from:
    - duraark-sessions

duraark-sda:
  image: duraark/duraark-sda:latest
  ports:
    - "5013:5013"

duraark-geometricenrichment:
  image: duraark/duraark-geometricenrichment:latest
  ports:
    - "5014:5014"
  privileged: true
  volumes_from:
    - duraark-sessions

duraark-digitalpreservation:
  image: duraark/duraark-digitalpreservation:latest
  ports:
    - "5015:5015"
  volumes:
    - duraark-sessions

workbench-ui:
  image: duraark/workbench-ui:latest
  ports:
    - "4200:4200"
  environment:
    - DURAARK_API_ENDPOINT=http://juliet.cgv.tugraz.at

web:
  image: duraark/api-gatekeeper:latest
  ports:
    - "80:80"
  links:
    - duraark-sessions
    - duraark-metadata
    - duraark-sda
    - duraark-geometricenrichment
    - duraark-digitalpreservation
    - workbench-ui
